Add `VaultId` as attribute for providers
The-Poolz/LockDeal-NFT-API pull request #104
Opened 2023-09-15 06:00 UTC by ArdenHide

2023-09-21 14:34 UTC, ArdenHide commented
Right now response for CollateralProvider look like:
```json
{
  "name": "Lock Deal NFT Pool: 8",
  "description": "Exclusively utilized by project administrators, this NFT serves as a secure vault for holding refundable tokens. It holds 0 for the main coin collector, 1 for the token collector, and DealProvider for the main coin holder, valid until 1696005796.",
  "image": "https://nft.poolz.finance/test/image?id=000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
  "attributes": [
    {
      "display_type": "number",
      "trait_type": "LeftAmount",
      "value": 50.0
    },
    {
      "display_type": "date",
      "trait_type": "FinishTime",
      "value": 1696005796
    },
    {
      "trait_type": "MainCoin",
      "value": "0xcd1ef832eb8a5a77842c440032e03c4330974d21"
    },
    {
      "trait_type": "Token",
      "value": "0x43d81a2cf49238484d6960de1df9d430c81cdffc"
    },
    {
      "display_type": "number",
      "trait_type": "LeftAmount_9",
      "value": 0.0
    },
    {
      "display_type": "number",
      "trait_type": "VaultId_9",
      "value": 1
    },
    {
      "trait_type": "ProviderName_9",
      "value": "DealProvider"
    },
    {
      "trait_type": "TokenName_9",
      "value": "Main coin Synthetic"
    },
    {
      "display_type": "number",
      "trait_type": "LeftAmount_10",
      "value": 50.0
    },
    {
      "display_type": "number",
      "trait_type": "VaultId_10",
      "value": 0
    },
    {
      "trait_type": "ProviderName_10",
      "value": "DealProvider"
    },
    {
      "trait_type": "TokenName_10",
      "value": "Token Synthetic"
    },
    {
      "display_type": "number",
      "trait_type": "LeftAmount_11",
      "value": 50.0
    },
    {
      "display_type": "number",
      "trait_type": "VaultId_11",
      "value": 1
    },
    {
      "trait_type": "ProviderName_11",
      "value": "DealProvider"
    },
    {
      "trait_type": "TokenName_11",
      "value": "Main coin Synthetic"
    },
    {
      "trait_type": "ProviderName",
      "value": "CollateralProvider"
    },
    {
      "trait_type": "TokenName",
      "value": "Main coin Synthetic"
    }
  ]
}
```

@Lomet
Question: Keep VaultId like it look right now, or you like to update this response?

2023-09-21 15:10 UTC, ArdenHide commented
Updated response for collateral

```json
{
  "name": "Lock Deal NFT Pool: 8",
  "description": "Exclusively utilized by project administrators, this NFT serves as a secure vault for holding refundable tokens. It holds 0 for the main coin collector, 1 for the token collector, and DealProvider for the main coin holder, valid until 1696005796.",
  "image": "https://nft.poolz.finance/test/image?id=000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
  "attributes": [
    {
      "display_type": "number",
      "trait_type": "LeftAmount",
      "value": 50.0
    },
    {
      "display_type": "date",
      "trait_type": "FinishTime",
      "value": 1696005796
    },
    {
      "trait_type": "MainCoin",
      "value": "0xcd1ef832eb8a5a77842c440032e03c4330974d21"
    },
    {
      "trait_type": "Token",
      "value": "0x43d81a2cf49238484d6960de1df9d430c81cdffc"
    },
    {
      "display_type": "number",
      "trait_type": "LeftAmount_9",
      "value": 0.0
    },
    {
      "display_type": "number",
      "trait_type": "VaultId_9",
      "value": 1
    },
    {
      "trait_type": "ProviderName_9",
      "value": "DealProvider"
    },
    {
      "trait_type": "TokenName_9",
      "value": "Main coin Synthetic"
    },
    {
      "display_type": "number",
      "trait_type": "LeftAmount_10",
      "value": 50.0
    },
    {
      "display_type": "number",
      "trait_type": "VaultId_10",
      "value": 0
    },
    {
      "trait_type": "ProviderName_10",
      "value": "DealProvider"
    },
    {
      "display_type": "number",
      "trait_type": "LeftAmount_11",
      "value": 50.0
    },
    {
      "display_type": "number",
      "trait_type": "VaultId_11",
      "value": 1
    },
    {
      "trait_type": "ProviderName_11",
      "value": "DealProvider"
    },
    {
      "trait_type": "TokenName_11",
      "value": "Main coin Synthetic"
    },
    {
      "trait_type": "ProviderName",
      "value": "CollateralProvider"
    },
    {
      "trait_type": "TokenName",
      "value": "Main coin Synthetic"
    }
  ]
}
```

2023-09-25 19:09 UTC, Lomet commented
TokenName_9 -> MainCoin Name
VaultId_9 ->  MainCoin VaultId

VaultId_10 -> Token VaultId
no need TokenName_11 and VaultId_11

no need ProviderName_9 ProviderName_10 ProviderName_11


all other names need to be: https://github.com/The-Poolz/LockDealNFT/blob/2d4ccbb8c32cd57c8bc4d9944f53f1c765cb9d51/contracts/AdvancedProviders/CollateralProvider/CollateralState.sol#L34-L36

main Coin Collector
token holder
main Coin Holder

* the `main Coin` and `vault Id` is the same for `main Coin Collector` and `main Coin Holder`

2023-09-25 19:10 UTC, Lomet requested changes
looks good - but the goal is a bit different for the CollateralProvider

https://github.com/The-Poolz/LockDeal-NFT-API/pull/104#issuecomment-1734315514

2023-09-26 09:47 UTC, ArdenHide commented
Now CollateralProvider response look like:

```json
{
  "name": "Lock Deal NFT Pool: 8",
  "description": "Exclusively utilized by project administrators, this NFT serves as a secure vault for holding refundable tokens. It holds 0 for the main coin collector, 1 for the token collector, and Main coin Synthetic for the main coin holder, valid until 1696005796.",
  "image": "https://nft.poolz.finance/test/image?id=123",
  "attributes": [
    {
      "display_type": "number",
      "trait_type": "LeftAmount",
      "value": 50.0
    },
    {
      "display_type": "date",
      "trait_type": "FinishTime",
      "value": 1696005796
    },
    {
      "trait_type": "MainCoin",
      "value": "0xcd1ef832eb8a5a77842c440032e03c4330974d21"
    },
    {
      "trait_type": "Token",
      "value": "0x43d81a2cf49238484d6960de1df9d430c81cdffc"
    },
    {
      "display_type": "number",
      "trait_type": "LeftAmount_9",
      "value": 0.0
    },
    {
      "display_type": "number",
      "trait_type": "MainCoin VaultId",
      "value": 1
    },
    {
      "trait_type": "MainCoin Name",
      "value": "Main coin Synthetic"
    },
    {
      "display_type": "number",
      "trait_type": "LeftAmount_10",
      "value": 50.0
    },
    {
      "display_type": "number",
      "trait_type": "Token VaultId",
      "value": 0
    },
    {
      "display_type": "number",
      "trait_type": "LeftAmount_11",
      "value": 50.0
    },
    {
      "trait_type": "ProviderName",
      "value": "CollateralProvider"
    },
    {
      "trait_type": "TokenName",
      "value": "Main coin Synthetic"
    }
  ]
}
```

2023-09-26 10:51 UTC, Lomet commented
- [ ] TokenName got the wrong value (need to be Token Synthetic (~Token Poolz))
 - [ ] LeftAmount_9 --> main Coin Collector Amount
 - [ ] LeftAmount_10 --> token holder Amount
 - [ ] LeftAmount_11 --> main Coin Holder Amount

2023-09-26 10:54 UTC, Lomet requested changes
Looks good, please check 
https://github.com/The-Poolz/LockDeal-NFT-API/pull/104#issuecomment-1735294895

2023-09-26 11:28 UTC, ArdenHide commented
> TokenName got the wrong value (need to be Token Synthetic (~Token Poolz))

![image](https://github.com/The-Poolz/LockDeal-NFT-API/assets/66203238/ee33f510-df83-4537-b96c-f241432a6797)
![image](https://github.com/The-Poolz/LockDeal-NFT-API/assets/66203238/6dab3f3c-9d82-42b9-9260-7994950abe96)

@Lomet

2023-09-26 11:46 UTC, ArdenHide commented on src/MetaDataAPI/Providers/Advanced/BundleProvider.cs
> +                }
All attributed will be included except the `VaultId`, because `we add all except the vault ID`

2023-09-26 11:51 UTC, Lomet commented
> > TokenName got the wrong value (need to be Token Synthetic (~Token Poolz))
> 
> ![image](https://user-images.githubusercontent.com/66203238/270639506-ee33f510-df83-4537-b96c-f241432a6797.png) ![image](https://user-images.githubusercontent.com/66203238/270639584-6dab3f3c-9d82-42b9-9260-7994950abe96.png)
> 
> @Lomet

right, So we don't need to check Main Coin. the token of the Is is Main Coin, 
just check the +2 for the Token

2023-09-27 10:07 UTC, Lomet approved these changes

2023-09-27 10:13 UTC, merged