Error on `MetadataNFTAPI` lambda
The-Poolz/LockDeal-NFT-API pull request #128
Opened 2023-09-27 14:49 UTC by ArdenHide

2023-09-28 10:02 UTC, Lomet commented on src/MetaDataAPI/Utils/DynamoDb.cs
>          return hash;
after catching it, it will return hash without having a picture there, 
better to return `5xx` error

2023-09-28 11:29 UTC, Lomet commented on src/MetaDataAPI/Utils/DynamoDb.cs
> +            return hash;
let's make sure the exception is due to the item exists, and not another error
no need to `return hash;` in `catch`, it will do it next line

2023-09-28 12:48 UTC, ArdenHide commented
![image](https://github.com/The-Poolz/LockDeal-NFT-API/assets/66203238/a9c2df62-d3c4-4f40-8e25-ba986b22282e)

2023-09-29 14:46 UTC, Lomet requested changes

2023-09-29 14:46 UTC, Lomet commented on src/MetaDataAPI/Utils/DynamoDb.cs
> +        catch (ConditionalCheckFailedException) { }
still not looks like final solution

2023-10-03 14:11 UTC, Lomet approved these changes

2023-10-03 14:28 UTC, merged